on: push
jobs:
  transition_jira_tickets:
    name: Transition
    runs-on: ubuntu-latest
    env:
      OWNER_NAME: ${{github.event.head_commit.author.name}}
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - uses: pmuraus/jira-ticket-transition-action@d0b439cc59fc63710030d79d3b691b075ac9d1d3
        with:
          targetTransition: "In Progress"
          message: "$OWNER_NAME started working on this issue"
          jiraBaseUrl: "peromed.atlassian.net"
          jiraEmail: "peromed@gmail.com"
          jiraToken: ${{secrets.JIRA_TOKEN}}
          fixVersion: "peterTestFixVersion"
          jiraProject: "IW"