on: push
jobs:
  transition_jira_tickets:
    name: Transition
    runs-on: ubuntu-latest
    env:
      OWNER_NAME: ${{github.event.head_commit.author.name}}
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - uses: pmuraus/jira-ticket-transition-action@a6805b24d0d81a90dfb7b20272e751f3d61bfcb6
        with:
          sourceTransition: "In Progress"
          targetTransition: "In Review"
          message: "$OWNER_NAME testing this action flow"
          jiraBaseUrl: "impactwrap.atlassian.net"
          jiraEmail: "hudson@inova.si"
          jiraToken: ${{secrets.JIRA_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          fixVersion: "peterTestFixVersion"
          jiraProject: "IW"
